// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package testnativedraggablelist.proxies;

public class TestItem implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject testItemMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "TestNativeDraggableList.TestItem";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		ItemID("ItemID"),
		SeqNbr("SeqNbr"),
		TestCheckbox("TestCheckbox");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public TestItem(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected TestItem(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject testItemMendixObject)
	{
		if (testItemMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, testItemMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.testItemMendixObject = testItemMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static testnativedraggablelist.proxies.TestItem initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new testnativedraggablelist.proxies.TestItem(context, mendixObject);
	}

	public static testnativedraggablelist.proxies.TestItem load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return testnativedraggablelist.proxies.TestItem.initialize(context, mendixObject);
	}

	public static java.util.List<testnativedraggablelist.proxies.TestItem> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> testnativedraggablelist.proxies.TestItem.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of ItemID
	 */
	public final java.lang.String getItemID()
	{
		return getItemID(getContext());
	}

	/**
	 * @param context
	 * @return value of ItemID
	 */
	public final java.lang.String getItemID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ItemID.toString());
	}

	/**
	 * Set value of ItemID
	 * @param itemid
	 */
	public final void setItemID(java.lang.String itemid)
	{
		setItemID(getContext(), itemid);
	}

	/**
	 * Set value of ItemID
	 * @param context
	 * @param itemid
	 */
	public final void setItemID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String itemid)
	{
		getMendixObject().setValue(context, MemberNames.ItemID.toString(), itemid);
	}

	/**
	 * @return value of SeqNbr
	 */
	public final java.lang.Integer getSeqNbr()
	{
		return getSeqNbr(getContext());
	}

	/**
	 * @param context
	 * @return value of SeqNbr
	 */
	public final java.lang.Integer getSeqNbr(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.SeqNbr.toString());
	}

	/**
	 * Set value of SeqNbr
	 * @param seqnbr
	 */
	public final void setSeqNbr(java.lang.Integer seqnbr)
	{
		setSeqNbr(getContext(), seqnbr);
	}

	/**
	 * Set value of SeqNbr
	 * @param context
	 * @param seqnbr
	 */
	public final void setSeqNbr(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer seqnbr)
	{
		getMendixObject().setValue(context, MemberNames.SeqNbr.toString(), seqnbr);
	}

	/**
	 * @return value of TestCheckbox
	 */
	public final java.lang.Boolean getTestCheckbox()
	{
		return getTestCheckbox(getContext());
	}

	/**
	 * @param context
	 * @return value of TestCheckbox
	 */
	public final java.lang.Boolean getTestCheckbox(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.TestCheckbox.toString());
	}

	/**
	 * Set value of TestCheckbox
	 * @param testcheckbox
	 */
	public final void setTestCheckbox(java.lang.Boolean testcheckbox)
	{
		setTestCheckbox(getContext(), testcheckbox);
	}

	/**
	 * Set value of TestCheckbox
	 * @param context
	 * @param testcheckbox
	 */
	public final void setTestCheckbox(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean testcheckbox)
	{
		getMendixObject().setValue(context, MemberNames.TestCheckbox.toString(), testcheckbox);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return testItemMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final testnativedraggablelist.proxies.TestItem that = (testnativedraggablelist.proxies.TestItem) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
