// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nanoflowcommonsitvisors.proxies;

public class DropDataItem implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject dropDataItemMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "NanoflowCommonsITvisors.DropDataItem";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		seqNbr("seqNbr"),
		itemId("itemId");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public DropDataItem(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected DropDataItem(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject dropDataItemMendixObject)
	{
		if (dropDataItemMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!dropDataItemMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.dropDataItemMendixObject = dropDataItemMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static nanoflowcommonsitvisors.proxies.DropDataItem initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new nanoflowcommonsitvisors.proxies.DropDataItem(context, mendixObject);
	}

	public static nanoflowcommonsitvisors.proxies.DropDataItem load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return nanoflowcommonsitvisors.proxies.DropDataItem.initialize(context, mendixObject);
	}

	/**
	 * @return value of seqNbr
	 */
	public final java.lang.Integer getseqNbr()
	{
		return getseqNbr(getContext());
	}

	/**
	 * @param context
	 * @return value of seqNbr
	 */
	public final java.lang.Integer getseqNbr(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.seqNbr.toString());
	}

	/**
	 * Set value of seqNbr
	 * @param seqnbr
	 */
	public final void setseqNbr(java.lang.Integer seqnbr)
	{
		setseqNbr(getContext(), seqnbr);
	}

	/**
	 * Set value of seqNbr
	 * @param context
	 * @param seqnbr
	 */
	public final void setseqNbr(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer seqnbr)
	{
		getMendixObject().setValue(context, MemberNames.seqNbr.toString(), seqnbr);
	}

	/**
	 * @return value of itemId
	 */
	public final java.lang.String getitemId()
	{
		return getitemId(getContext());
	}

	/**
	 * @param context
	 * @return value of itemId
	 */
	public final java.lang.String getitemId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.itemId.toString());
	}

	/**
	 * Set value of itemId
	 * @param itemid
	 */
	public final void setitemId(java.lang.String itemid)
	{
		setitemId(getContext(), itemid);
	}

	/**
	 * Set value of itemId
	 * @param context
	 * @param itemid
	 */
	public final void setitemId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String itemid)
	{
		getMendixObject().setValue(context, MemberNames.itemId.toString(), itemid);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return dropDataItemMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final nanoflowcommonsitvisors.proxies.DropDataItem that = (nanoflowcommonsitvisors.proxies.DropDataItem) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
